server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# aws.access-key = ${AWS_ACCESS_KEY}
# aws.secret-key = ${AWS_SECRET_KEY}

spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = viraldobariya33@gmail.com
spring.mail.password = ${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.check-template-location=true
spring.thymeleaf.suffix=.html